apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: anotherclass-435
  name: cust-4351
  labels:
    part-of: k8s-anotherclass
    component: backend-server
    name: cust
    instance: cust-4351
    version: 4.0.0
    managed-by: kubectl
spec:
  selector:
    matchLabels:
      part-of: k8s-anotherclass
      component: backend-server
      name: cust
      instance: cust-4351
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        part-of: k8s-anotherclass
        component: backend-server
        name: cust
        instance: cust-4351
        version: 4.0.0
    spec:
      containers:
        - name: cust-4351
          # 1pro는 본인의 dockerhub username으로 변경해 주세요.
          image: 1pro/api-tester:4.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
          resources:
            requests:
              cpu: "50m"
              memory: "200Mi"
            limits:
              cpu: "100m"
              memory: "200Mi"
          envFrom:
            - configMapRef:
                name: cust-4351-properties
          startupProbe:
            httpGet:
              path: "/startup"
              port: 8080
            periodSeconds: 5
            failureThreshold: 24
          readinessProbe:
            httpGet:
              path: "/readiness"
              port: 8080
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: "/liveness"
              port: 8080
            periodSeconds: 10
            failureThreshold: 3
          volumeMounts:
            - name: secret-datasource
              mountPath: /usr/src/myapp/datasource
      volumes:
        - name: secret-datasource
          secret:
            secretName: api-tester-4351-postgresql